### ISSUE TITLE
3B. Add Google Analytics Tracking.

### ISSUE THREAD

**Issue by dc-tonglec** [Yanlun-Li/ClinicWebsite#1]
Here is one of the topic on how to add Google Analytics Tracking.
https://uwaterloo.ca/web-resources/wcms-users/training-and-support/wcms-how-documents/google-analytics

**Comment by ML72** [comment]
the U waterloo link does not work anymore, but I can search up how to do this on google: https://support.google.com/analytics/answer/1008015?hl=en

**Comment by ML72** [comment]
@dc-tonglec which account do i use to do google analytics? the gmail used for @Yanlun-Li 's account?

**Comment by dc-tonglec** [comment]
User the yanlunclinic@gmail.com Google account.

**Comment by ML72** [comment]
https://www.crazyegg.com/blog/google-analytics/

**Comment by ML72** [comment]
https://support.google.com/analytics/answer/9303323?hl=en&utm_id=ad#zippy=%2Cin-this-article

**Comment by ML72** [comment]
Addressed in: https://github.com/Yanlun-Li/ClinicWebsite/commit/96eecd7d374bf511d31ed1f76e312e0b7886a34c

No data has been collected yet despite testing. According to this link, we may need to wait 24 hours and resolve any further issues if they arise: https://support.google.com/analytics/answer/9311124?hl=en&utm_id=ad

**Comment by ML72** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/45986807/146652148-211af6f2-7f73-449d-9bba-7c657e6b2374.png">
Update: google analytics is receiving traffic so it works (this one user so far is me though)
