### ISSUE TITLE
2B. Add animations and cool effects as appropriate

### ISSUE THREAD

**Issue by Yanlun-Li** [Yanlun-Li/ClinicWebsite#15]
Use animate.css and other cool libraries to style up the project!

We'd better to be able to present new activities, like Covide19 shot.

**Comment by ML72** [comment]
Added this commit: https://github.com/Yanlun-Li/ClinicWebsite/commit/3a561a5a597fdd6b5730cdb4307aca870a8b5e4d
This is for entrance effects; please let me know if there is any other animations we can do

**Comment by ML72** [comment]
all issues addressed, reopen if there are additional animations to add
