### ISSUE TITLE
Add Google Map to the web page & update footer

### ISSUE THREAD

**Issue by dc-tonglec** [Yanlun-Li/ClinicWebsite#21]

**Comment by dc-tonglec** [comment]
Please reference this page for Google map.
https://yanlun-li-medical-practice-pc.business.site/
Also make similar footer

**Comment by ML72** [comment]
Addressed in this commit: https://github.com/Yanlun-Li/ClinicWebsite/commit/c30e6b8a347b4595d389513c7cd155d5856ba604
