### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by dc-tonglec** [Yanlun-Li/ClinicWebsite#22]
1. Update the following, Remove the middle two highlight rows. And make the area narrower.
![image](https://user-images.githubusercontent.com/85365077/145736212-a499a65e-f001-42e6-b5b2-3851ce328a57.png)

2.

**Comment by ML72** [comment]
- factor out language change button from navbar
- better place for office hours (remove from footer)
- top panel a bit smaller (?)
- add animation

**Comment by ML72** [comment]
https://usersnap.com/blog/design-language-switch/

**Comment by ML72** [comment]
all aforementioned issues addressed in commits
